function sharesList = getShareListbyindex(idx_list)
underlyingNames = { ...
    'Eurostoxx'; 'AirLiquide'; 'Allianz'; 'InBev'; 'Arcelor'; 'ASML'; ...
    'Generali'; 'AXA'; 'BBVA'; 'Santander'; 'BASF'; 'Bayer'; ...
    'BMW'; 'BNP'; 'Carrefour'; 'StGobain'; 'CRH'; 'Daimler'; ...
    'Danone'; 'DB'; 'DT'; 'EON'; 'ENEL'; 'ENI'; 'Essilor'; ...
    'FT'; 'GdF'; 'Iberdrola'; 'Inditex'; 'ING'; 'ISP'; ...
    'Philips'; 'Oreal'; 'LVMH'; 'MunichRe'; 'Nokia'; 'Repsol'; ...
    'RWE'; 'Sanofi'; 'SAP'; 'Schneider'; 'Siemens'; 'SocGen'; ...
    'Telefonica'; 'Total'; 'Unibail'; 'Unicredit'; 'Unilever'; ...
    'Vinci'; 'Vivendi'; 'Volkswagen' ...
};

sharesList = underlyingNames(idx_list);
sharesList = sharesList(:);
end